config/routes.rb
Bookmarks::Application.routes.draw do

  get 'tags/:tag',to: 'bookmarks#index', as: :tag

  resources :bookmarks  
  resources :pages

  root 'pages#index'

  

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :page
  acts_as_taggable
  
  validates :name, uniqueness: true
  validates :short_link, presence: true, uniqueness:  true
  
  extend Search
  
  def fill_params
    domain = self.short_link.split("//").last.split("/").first
    
    agent = Mechanize.new
      page = agent.get(self.short_link)
      
      self.page = Page.find_by_domain(domain)
      self.page ||= Page.create(domain: domain)
      
      self.name = page.title if self.name == ''
      d = page.at('meta[@name="description"]')
      self.description = d[:content] if d
  end
  
  def tinyfy
    url = URI.parse('http://tinyurl.com/')
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.get('/api-create.php?url=' + self.short_link)
     }
     self.short_link = res.body
  end
  
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :bookmarks, dependent: :destroy
  
  validates :domain, presence: true, uniqueness: true
  
  extend Search
end

app/models/search.rb
module Search
  def search(params = {})  
    conditions = []
    
    if params
      conditions << params.keys.reduce('') do |result, key|
        if params[key] != "" && key.to_s != "utf8" && key.to_s != "action" && key.to_s != "controller"
          result + key.to_s + ' LIKE ? AND ' 
        else
          result
        end
      end.chomp('AND ')
      
      params.each do |key, value| 
        conditions << "%#{value}%" if params[key] != "" && key.to_s != "utf8" && 
                                     key.to_s != "action" && key.to_s != "controller" 
      end
    end
    if conditions.length > 1
      find(:all, :conditions => conditions)
    else
      find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  
  # GET /bookmarks
  # GET /bookmarks.json
  
  def index
    if params[:tag]
      @bookmarks = Bookmark.tagged_with(params[:tag])
    else
      @bookmarks = Bookmark.search(params) 
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.fill_params
    @bookmark.tinyfy
    
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bookmark }
      else
        format.html { render action: 'new' }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to pages_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:name, :short_link,
       :description, :page_id, :tag_list)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.search(params)
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @bookmarks = Bookmark.search(params[:search])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:domain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper  
  def search_name(*args)
    if args 
      args.each do |key, value|
       # where([key name LIKE ?', "%#{search}%"]])
      end
    end
    
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      scoped
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/all/search_form.html.erb
<%= simple_form_for @search_results, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :short_link, label: "URL" %>
  <%= f.label :tags %>
  <%= f.simple_fields_for :tags do |builder| %>
  	<%= builder.input :name, label: false %>
  	<%= builder.label "Destroy Tag", class: "label label-default"%>
  	<%= builder.check_box :_destroy %>
  	
  <% end %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bookmarks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bookmarks/_form.html.erb
<%= simple_form_for @bookmark, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name, label: "Name (type or download from meta-data)" %>
  <%= f.input :short_link, label: "URL" %>
  <%= f.input :tag_list, label: "Tag List (Separate by comas):" %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bookmarks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bookmarks/_index.html.erb
<%- model_class = Bookmark -%>

<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>

<%= form_tag bookmarks_path, :method => 'get', :html => { :class => 'form-vertical' } do %>
  <h4>Search By</h4>
	<div class="control-group">
  		<%= label_tag :name, "Name", class: "control-label" %>
    	<div class="controls">
    	<%= text_field_tag :name, params[:name], class: "text-field" %>
    	</div>
  	</div>
    <div class="control-group">
  		<%= label_tag :description, "Description", class: "control-label" %>
    	<div class="controls">
    	<%= text_field_tag :description, params[:description], class: "text-field" %>
		</div>
  	</div>
    <div class="control-group">
		<%= label_tag :short_link, "Short_link", class: "control-label" %>
    	<div class="controls">
    	<%= text_field_tag :short_link, params[:short_link], class: "text-field" %>
    	</div>
  	</div>
  	<div class="form-actions">
    <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
    </div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
       <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:short_link) %></th>
      <th><%= model_class.human_attribute_name(:page) %></th>      
      <th><%= model_class.human_attribute_name(:tag_list) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% bookmarks.each do |bookmark| %>
      <tr>
        <td><%= link_to bookmark.name, bookmark_path(bookmark) %></td>
        <td><%= bookmark.description %></td>
        <td><%= bookmark.short_link %></td>
        <td><%= bookmark.page.domain %></td>
        <td><%= raw bookmark.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "label" }.join(', ') %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bookmark_path(bookmark), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bookmark_path(bookmark),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bookmark_path,
            :class => 'btn btn-primary' %>

app/views/bookmarks/edit.html.erb
<%- model_class = Bookmark -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bookmarks/index.html.erb
<%= render "index", bookmarks: @bookmarks, tags: @tags %>

app/views/bookmarks/new.html.erb
<%- model_class = Bookmark -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bookmarks/show.html.erb
<%- model_class = Bookmark -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bookmark.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_link) %>:</strong></dt>
  <dd><%= link_to @bookmark.short_link, @bookmark.short_link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:page_id) %>:</strong></dt>
  <dd><%= @bookmark.page.domain %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @bookmark.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tag_list) %>:</strong></dt>
  <dd><%= raw @bookmark.tag_list.map { |tag| link_to tag, tag_path(tag), class: "label" }.join(", ") %></dd>
</dl>

	
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pages_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bookmark_path(@bookmark), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bookmark_path(@bookmark),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bookmarks" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Bookmarks", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Pages", pages_path  %></li>
              <li><%= link_to "Bookmarks", bookmarks_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for @page, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :domain %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pages/index.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_tag pages_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :domain, params[:domain] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:domain) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.domain, page_path(page) %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      page_path(page),
                      :method => :delete,
                      :data => { :confirm => "Are you sure?\n\nAll bookmarks belonged to this page will be also destroyed!" },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New bookmark",
            new_bookmark_path,
            :class => 'btn btn-primary' %>

app/views/pages/new.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pages/show.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:domain) %>:</strong></dt>
  <dd><%= @page.domain %></dd>
</dl>

<%= render "bookmarks/index", bookmarks: @page.bookmarks %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pages_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_page_path(@page), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              page_path(@page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>